class UserInfoFields:
    USER_ID = 'user_id'
    EMAIL = 'email'
    FIRST_NAME = 'first_name'
    LAST_NAME = 'last_name'
    CITY = 'city'
    GRADE = 'grade'
    CAN_ACCESS_PLATFORM = 'can_access_platform'
    MANAGER_EMAIL = 'manager_email'
    MANAGER_ID = 'manager_id'
    DEPARTMENT = 'department'
    COUNTRY = 'country'
    BUSINESS_UNIT = 'business_unit'
    EXTRA_DATA = 'extra_data'
